Initial work on action
inloco/actions-setup-go pull request #1
Opened 2022-02-03 16:49 UTC by paulolieuthier

2022-02-04 02:22 UTC, t0rr3sp3dr0 requested changes

2022-02-04 02:22 UTC, t0rr3sp3dr0 commented on action.yml
> +      ${{ runner.os }}-go-dependencies-
I don't think we should make this configurable. This is an opinionated setup for Go, if the user disables the cache, it's better to just use actions/setup-go instead.

2022-02-04 02:22 UTC, t0rr3sp3dr0 commented on action.yml
> +      exit 1
This should not be in the setup action. We can create another action that performs various checks for Go, Java, and other languages. But this is out of scope for a setup action.

2022-02-04 14:26 UTC, paulolieuthier commented on action.yml
> +    run: sudo apt update && sudo apt install -y gcc
I've seen projects that only need `gcc` as an extra package.

> We could have an input as part of the bootstrap action to install packages listed on the input, where the user could list gcc and other dependencies required for the build.

Great idea.

2022-02-04 14:26 UTC, paulolieuthier commented on action.yml
> +      exit 1
Fair enough.

2022-02-04 14:26 UTC, paulolieuthier commented on action.yml
> +      ${{ runner.os }}-go-dependencies-
Fair enough.

2022-02-04 14:29 UTC, paulolieuthier commented on action.yml
> +      exit 1
The thing is that of the languages we use, I think only Go has a default formatting tool. incognia-backend, for instance, uses a Gradle plugin for that.

2022-02-04 16:19 UTC, t0rr3sp3dr0 commented on action.yml
> +      exit 1
Python algo has a well-defined formatting style: https://www.python.org/dev/peps/pep-0008/

2022-02-04 16:30 UTC, t0rr3sp3dr0 commented on action.yml
> +      exit 1
I would be also to incorporate this tool across the company

2022-02-08 22:34 UTC, t0rr3sp3dr0 approved these changes

2022-02-08 22:34 UTC, t0rr3sp3dr0 commented on action.yml
> +    if: inputs.cache
You forgot to remove this line

2022-02-09 17:15 UTC, merged